# /site/blueprints/fields/pagesettings.yml
type: group
fields:
  pageSettings:
    label: Page Settings & SEO
    type: headline
    numbered: false
  title:
    label: Title
    type:  text
  metadescription:
    label: Meta Description
    type:  textarea
    buttons: false
    validate:
      maxLength: 320
  socialimage:
    label: Social Image
    help: Preview image for Twitter, Facebook and in iMessages. Suggested size 1200 x 630.
    type: image
