title: Page
pages: true
files: true
  fields:
    caption:
      label: Title
      type: text
fields:
  pageSettings:
    extends: pagesettings
  previewfiles:
    type: previewfiles
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  
