fields:
  title:
    label: Title
    type:  text
  trackingcode:
    label: Google Tags Tracking Code
    help: Copy and paste from your google analytics dashboard.
    type:  textarea
    buttons: false
